name: Warden PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          type -p gh >/dev/null || {
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
          }

      - name: Run Warden Review
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Dry run only in CI - don't auto-fix
          warden \
            --dry-run \
            --reviewers security,performance \
            --test-strategy affected \
            --comment-on-pr \
            --output-format markdown \
            --save-report warden-report.md \
            --protect-branches main,master,production

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: warden-report
          path: warden-report.md
